version: '3.3'
services:

  notejam-db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Pass@123
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    networks:
      - notejam-network 

  notejam-app:
    image: "nodejs-docker:0.0.2"
    links:
      - notejam-db
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: "notejam-db"
      MYSQL_ROOT_PASSWORD: "Pass@123"
      MYSQL_TCP_PORT: "3306"
      NOTEJAM_HOST: "notejam-app"
      NOTEJAM_PORT: "8080"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - notejam-network
networks:
  notejam-network:
    driver: overlay
volumes:
  sql:
  
